### ISSUE TITLE
Testing realsense wrapper (public) to replace our private repo.

### ISSUE THREAD

**Issue by inkyusa** [ethz-asl/mav_dji_ros_interface#14]
@fmina @raghavkhanna We need to clean up our private repo (realsense wrapper, https://github.com/ethz-asl/realsense_ros) or test this repo (https://github.com/ethz-asl/realsense).

**Comment by fmina** [comment]
can we close this?

**Comment by inkyusa** [comment]
I made a stripped-down version of realsense_ros, realsense_ros_simple, https://github.com/inkyusa/realsense_ros_simple that only enables IMU and fisheye camera. Only compilation is checked and we need to test this
