### ISSUE TITLE
Thrust from Gamepad F710

### ISSUE THREAD

**Issue by asharmarx** [ethz-asl/mav_dji_ros_interface#20]
Hi, this might sound like a dumb question but I can't see any thrust coming from the Gamepad when I echo the roll pitch yaw thrust topic. I am trying to test it in the DJI Simulator, I don't know if that makes a difference. Any help will be greatly appreciated!

**Comment by asharmarx** [comment]
I figured it out. It was a connection error.

**Comment by inkyusa** [comment]
@asharmarx Happy to hear that you could find the error :)
Cheers,
