### ISSUE TITLE
What is wrong with me?

### ISSUE THREAD

**Issue by LZMHIT** [ethz-asl/mav_dji_ros_interface#26]
Dear Author:
    Recently, I git the mav_dji_ros_interface project in my computer, and I follow the wiki page you list. But I found it dosen't work, for example, I find the package mav_dji_ros_interface is none, it didn't contain any launch file, while the command in the wiki package shows that it dose exist, I don't know while, Could you please tell me how to deal with that. Thanks sincerely!

**Comment by inkyusa** [comment]
Dear LZMHIT,
The folder "mav_dji_ros_interface" only contains package.xml file that describes dependencies to other packages such as dji_sdk_lib, dji_comm, dji_interface.
Please have a look ROS tutorial (http://wiki.ros.org/ROS/Tutorials/CreatingPackage) section 5.

BTW, launch files you are looking for are located at https://github.com/ethz-asl/mav_dji_ros_interface/tree/master/dji_interface/launch
Best.
