### ISSUE TITLE
I can't get state information from M100's IMU

### ISSUE THREAD

**Issue by wqwanghanzhang** [ethz-asl/mav_dji_ros_interface#27]
Hi,thanks for your sharing:

my question is about msf,I can't get M100's imu's state information,and I've run the rovio with zr300 good ,when I roslaunch raven_indoor_rovio_nMPC_trj_realsense.launch the information of the screen like this:

wq@wqz:~/catkin_test/src/mav_dji_ros_interface/dji_interface/launch$ roslaunch raven_indoor_rovio_nMPC_trj_realsense.launch 
... logging to /home/wq/.ros/log/61366954-6ec0-11e8-9583-e0d55e131bd1/roslaunch-wqz-12639.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wqz:43965/

SUMMARY
========

CLEAR PARAMETERS
 * /raven/dji_interface/
 * /raven/mav_linear_mpc/
 * /raven/pose_sensor_rovio/

PARAMETERS
 * /capabilities: [['Core', 'core',...
 * /raven/dji_interface/app_id: 1040678
 * /raven/dji_interface/baudrate: 921600
 * /raven/dji_interface/device: /dev/ttyUSB0
 * /raven/dji_interface/enc_key: a41335b074411eb34...
 * /raven/dji_interface/gps_updae_rate: 1
 * /raven/dji_interface/imu_update_rate: 50
 * /raven/dji_interface/magnetometer_update_rate: 1
 * /raven/dji_interface/rc_update_rate: 10
 * /raven/dji_interface/status_update_rate: 1
 * /raven/dji_interface/thrust_constant: 1.2
 * /raven/dji_interface/time_stamp_update_rate: 1
 * /raven/mav_linear_mpc/KF_observer/P0_angular_velocity: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_attitude: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_force: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_position: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_torque: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_velocity: 0.1
 * /raven/mav_linear_mpc/KF_observer/calibration_duration: 5
 * /raven/mav_linear_mpc/KF_observer/drag_coefficients: [0.01, 0.01, 0]
 * /raven/mav_linear_mpc/KF_observer/external_forces_limit: [5.0, 5.0, 3.0]
 * /raven/mav_linear_mpc/KF_observer/external_moments_limit: [20.0, 20.0, 20.0]
 * /raven/mav_linear_mpc/KF_observer/omega_limit: [3.0, 3.0, 2.0]
 * /raven/mav_linear_mpc/KF_observer/pitch_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/pitch_gain: 1.097
 * /raven/mav_linear_mpc/KF_observer/pitch_omega: 7.07
 * /raven/mav_linear_mpc/KF_observer/q_angular_velocity: 0.02
 * /raven/mav_linear_mpc/KF_observer/q_attitude: 0.015
 * /raven/mav_linear_mpc/KF_observer/q_force: 0.05
 * /raven/mav_linear_mpc/KF_observer/q_position: 0.01
 * /raven/mav_linear_mpc/KF_observer/q_torque: 0.05
 * /raven/mav_linear_mpc/KF_observer/q_velocity: 0.025
 * /raven/mav_linear_mpc/KF_observer/r_attitude: 0.001
 * /raven/mav_linear_mpc/KF_observer/r_position: 0.0001
 * /raven/mav_linear_mpc/KF_observer/r_velocity: 0.00012
 * /raven/mav_linear_mpc/KF_observer/roll_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/roll_gain: 1.101
 * /raven/mav_linear_mpc/KF_observer/roll_omega: 7.07
 * /raven/mav_linear_mpc/KF_observer/yaw_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/yaw_gain: 1.0
 * /raven/mav_linear_mpc/KF_observer/yaw_omega: 4.0
 * /raven/mav_linear_mpc/K_yaw: 1.8
 * /raven/mav_linear_mpc/Ki_xy: 0.2
 * /raven/mav_linear_mpc/Ki_z: 0.3
 * /raven/mav_linear_mpc/antiwindup_ball: 0.4
 * /raven/mav_linear_mpc/capability_group: Core
 * /raven/mav_linear_mpc/drag_coefficients: [0.01, 0.01, 0.0]
 * /raven/mav_linear_mpc/enable_integrator: True
 * /raven/mav_linear_mpc/enable_offset_free: True
 * /raven/mav_linear_mpc/mass: 2.895
 * /raven/mav_linear_mpc/pitch_gain: 1.097
 * /raven/mav_linear_mpc/pitch_max: 0.436332312999
 * /raven/mav_linear_mpc/pitch_time_constant: 0.267
 * /raven/mav_linear_mpc/position_error_integration_limit: 2
 * /raven/mav_linear_mpc/prediction_sampling_time: 0.1
 * /raven/mav_linear_mpc/q_pitch: 20
 * /raven/mav_linear_mpc/q_roll: 20
 * /raven/mav_linear_mpc/q_vx: 10
 * /raven/mav_linear_mpc/q_vy: 10
 * /raven/mav_linear_mpc/q_vz: 25
 * /raven/mav_linear_mpc/q_x: 80
 * /raven/mav_linear_mpc/q_y: 80
 * /raven/mav_linear_mpc/q_z: 100
 * /raven/mav_linear_mpc/r_dpitch: 0.2
 * /raven/mav_linear_mpc/r_droll: 0.2
 * /raven/mav_linear_mpc/r_dthrust: 0.0025
 * /raven/mav_linear_mpc/r_pitch: 110
 * /raven/mav_linear_mpc/r_roll: 110
 * /raven/mav_linear_mpc/r_thrust: 2
 * /raven/mav_linear_mpc/roll_gain: 1.101
 * /raven/mav_linear_mpc/roll_max: 0.436332312999
 * /raven/mav_linear_mpc/roll_time_constant: 0.253
 * /raven/mav_linear_mpc/sampling_time: 0.02
 * /raven/mav_linear_mpc/thrust_max: 20
 * /raven/mav_linear_mpc/thrust_min: 5
 * /raven/mav_linear_mpc/use_rc_teleop: True
 * /raven/mav_linear_mpc/verbose: False
 * /raven/mav_linear_mpc/yaw_rate_max: 1.57079632679
 * /raven/pose_sensor_rovio/core/core_noise_acc: 0.083
 * /raven/pose_sensor_rovio/core/core_noise_accbias: 5e-05
 * /raven/pose_sensor_rovio/core/core_noise_gyr: 0.0013
 * /raven/pose_sensor_rovio/core/core_noise_gyrbias: 1.3e-06
 * /raven/pose_sensor_rovio/core/data_playback: True
 * /raven/pose_sensor_rovio/core/fixed_bias: 0
 * /raven/pose_sensor_rovio/pose_sensor/fixed_scale: 1.0
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/x: 0.0312049862392
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/y: 0.0639849685927
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/z: -0.0618914813697
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/w: 0.0318837925519
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/x: 0.704754446355
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/y: -0.708229159884
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/z: -0.0267591331242
 * /raven/pose_sensor_rovio/pose_sensor/pose_absolute_measurements: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_delay: -0.0358408930047
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_p_ic: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_p_wv: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_q_ic: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_q_wv: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_scale: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_measurement_world_sensor: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_meas_p: 0.2
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_meas_q: 0.09
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_p_ic: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_p_wv: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_q_ic: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_q_wv: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_scale: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_use_fixed_covariance: True
 * /raven/trajectory_sampler/publish_whole_trajectory: True
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /raven/
    dji_interface (dji_interface/dji_interface_node)
    mav_linear_mpc (mav_linear_mpc/mav_linear_mpc_node)
    pose_sensor_rovio (msf_updates/pose_sensor)
    trajectory_sampler (mav_trajectory_generation_ros/trajectory_sampler_node)
    world_to_odom (tf/static_transform_publisher)
    world_to_vicon (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[raven/dji_interface-1]: started with pid [12660]
process[raven/pose_sensor_rovio-2]: started with pid [12661]
process[raven/mav_linear_mpc-3]: started with pid [12663]
process[raven/trajectory_sampler-4]: started with pid [12680]
process[raven/world_to_vicon-5]: started with pid [12687]
device: /dev/ttyUSB0
process[raven/world_to_odom-6]: started with pid [12706]
drone_version: M100
[ INFO] [1528875232.429506618]: Initialized trajectory sampler.
[ INFO] [1528875232.430707042]: parameters loaded correctly
ERROR openSerial,line 169: Failed to open serial device /dev/ttyUSB0
ERROR init,line 58: Failed to start serial device
[ INFO] [1528875232.430823644]: Succeed to create thread for readPoll and sendPoll
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0613 15:33:52.439970 12680 trajectory_sampling.cpp:38] Dimension has to be 3 or 4, but is 0
[ INFO] [1528875232.440423603]: /raven/pose_sensor_rovio:
	subscribed to topics:
	advertised topics:
		/rosout
		/tf
		/raven/pose_sensor_rovio/core/parameter_descriptions
		/raven/pose_sensor_rovio/core/parameter_updates
		/raven/msf_core/state_out
		/raven/msf_core/correction
		/raven/msf_core/pose
		/raven/msf_core/odometry
		/raven/msf_core/pose_after_update
		/raven/msf_core/ext_state
		/raven/msf_core/cov_core
		/raven/msf_core/cov_aux
		/raven/msf_core/cov_core_aux

and when I run rviz ,there is no state information of M100's imu demonstrate on the rviz
I guess "/raven/status" is related to the M100's IMU state information,but there is no data from it.
and I found some errors :
ERROR openSerial,line 169: Failed to open serial device /dev/ttyUSB0
ERROR init,line 58: Failed to start serial device
ERROR sendData,line 47: Port closedERROR sendData,line 47: Port closedERROR sendData,line 47: Port closed==============
DJI Comm initialized correctly.
ERROR activate,line 391: Please call getDroneVersion first.
ERROR sendData,line 47: Port closedBroadcast call back received 

I guess maybe there are some problems related to hardware,and I'm sure i follow the Serial Wiring wiki,and here is the picture and the firmare is V1.3.1.00 (2016.04.13).and the status of the M100 is connected with remote controller .I'm not sure if this is right, because the wiki didn't tell if M100 should connet rc when I read the state of M100's IMU's parameters.(sorry,my english is not good)                         so can you help me with that?

**Comment by inkyusa** [comment]
Hello wq,
It seems either H/W (USB-serial) or software setup issues.
When you plug a USB-serial device into your computer, can you see /dev/ttyUSB0 or /dev/ttyUSBx (by typing "ls -al /dev/" before plug-in and after plug-in)?
If yes, could you try to change the name of the device (default: /dev/ttyUSB0) from mav_dji_ros_interface/dji_interface/cfg/params.yaml to newly detected one?

**Comment by wqwanghanzhang** [comment]
Hi,inkyusa
thank you for your reply,I 've tried your method and when I plug  USB-serial device into the computer and  type "ls -al /dev/" there is /dev/ttyUSB0 appeared.before I plug in,I type "ls -al /dev/",there is no  /dev/ttyUSB0 .the newly detected one is /dev/ttyUSB0,and the default one in yaml is the same.So I think it is not  software setup issue.and the hardware setup is like the picture on the bottom,I connect the M100 with rc,and I run the raven_indoor_rovio_nMPC_trj_realsense.launch.and I find that the errors are same before I turn on the M100's power and after  turn on.
here is the whole log(sorry part of the log's size is too big,but I find no way to mini them):
wq@wqz:~/catkin_test/src/mav_dji_ros_interface/dji_interface/launch$ roslaunch raven_indoor_rovio_nMPC_trj_realsense.launch 
... logging to /home/wq/.ros/log/28784fd4-6fb4-11e8-b801-e0d55e131bd1/roslaunch-wqz-7770.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wqz:39255/

SUMMARY
========

CLEAR PARAMETERS
 * /raven/dji_interface/
 * /raven/mav_linear_mpc/
 * /raven/pose_sensor_rovio/

PARAMETERS
 * /capabilities: [['Core', 'core',...
 * /raven/dji_interface/app_id: 1040678
 * /raven/dji_interface/baudrate: 921600
 * /raven/dji_interface/device: /dev/ttyUSB0
 * /raven/dji_interface/enc_key: a41335b074411eb34...
 * /raven/dji_interface/gps_updae_rate: 1
 * /raven/dji_interface/imu_update_rate: 50
 * /raven/dji_interface/magnetometer_update_rate: 1
 * /raven/dji_interface/rc_update_rate: 10
 * /raven/dji_interface/status_update_rate: 1
 * /raven/dji_interface/thrust_constant: 1.2
 * /raven/dji_interface/time_stamp_update_rate: 1
 * /raven/mav_linear_mpc/KF_observer/P0_angular_velocity: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_attitude: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_force: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_position: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_torque: 0.1
 * /raven/mav_linear_mpc/KF_observer/P0_velocity: 0.1
 * /raven/mav_linear_mpc/KF_observer/calibration_duration: 5
 * /raven/mav_linear_mpc/KF_observer/drag_coefficients: [0.01, 0.01, 0]
 * /raven/mav_linear_mpc/KF_observer/external_forces_limit: [5.0, 5.0, 3.0]
 * /raven/mav_linear_mpc/KF_observer/external_moments_limit: [20.0, 20.0, 20.0]
 * /raven/mav_linear_mpc/KF_observer/omega_limit: [3.0, 3.0, 2.0]
 * /raven/mav_linear_mpc/KF_observer/pitch_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/pitch_gain: 1.097
 * /raven/mav_linear_mpc/KF_observer/pitch_omega: 7.07
 * /raven/mav_linear_mpc/KF_observer/q_angular_velocity: 0.02
 * /raven/mav_linear_mpc/KF_observer/q_attitude: 0.015
 * /raven/mav_linear_mpc/KF_observer/q_force: 0.05
 * /raven/mav_linear_mpc/KF_observer/q_position: 0.01
 * /raven/mav_linear_mpc/KF_observer/q_torque: 0.05
 * /raven/mav_linear_mpc/KF_observer/q_velocity: 0.025
 * /raven/mav_linear_mpc/KF_observer/r_attitude: 0.001
 * /raven/mav_linear_mpc/KF_observer/r_position: 0.0001
 * /raven/mav_linear_mpc/KF_observer/r_velocity: 0.00012
 * /raven/mav_linear_mpc/KF_observer/roll_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/roll_gain: 1.101
 * /raven/mav_linear_mpc/KF_observer/roll_omega: 7.07
 * /raven/mav_linear_mpc/KF_observer/yaw_damping: 1.0
 * /raven/mav_linear_mpc/KF_observer/yaw_gain: 1.0
 * /raven/mav_linear_mpc/KF_observer/yaw_omega: 4.0
 * /raven/mav_linear_mpc/K_yaw: 1.8
 * /raven/mav_linear_mpc/Ki_xy: 0.2
 * /raven/mav_linear_mpc/Ki_z: 0.3
 * /raven/mav_linear_mpc/antiwindup_ball: 0.4
 * /raven/mav_linear_mpc/capability_group: Core
 * /raven/mav_linear_mpc/drag_coefficients: [0.01, 0.01, 0.0]
 * /raven/mav_linear_mpc/enable_integrator: True
 * /raven/mav_linear_mpc/enable_offset_free: True
 * /raven/mav_linear_mpc/mass: 2.895
 * /raven/mav_linear_mpc/pitch_gain: 1.097
 * /raven/mav_linear_mpc/pitch_max: 0.436332312999
 * /raven/mav_linear_mpc/pitch_time_constant: 0.267
 * /raven/mav_linear_mpc/position_error_integration_limit: 2
 * /raven/mav_linear_mpc/prediction_sampling_time: 0.1
 * /raven/mav_linear_mpc/q_pitch: 20
 * /raven/mav_linear_mpc/q_roll: 20
 * /raven/mav_linear_mpc/q_vx: 10
 * /raven/mav_linear_mpc/q_vy: 10
 * /raven/mav_linear_mpc/q_vz: 25
 * /raven/mav_linear_mpc/q_x: 80
 * /raven/mav_linear_mpc/q_y: 80
 * /raven/mav_linear_mpc/q_z: 100
 * /raven/mav_linear_mpc/r_dpitch: 0.2
 * /raven/mav_linear_mpc/r_droll: 0.2
 * /raven/mav_linear_mpc/r_dthrust: 0.0025
 * /raven/mav_linear_mpc/r_pitch: 110
 * /raven/mav_linear_mpc/r_roll: 110
 * /raven/mav_linear_mpc/r_thrust: 2
 * /raven/mav_linear_mpc/roll_gain: 1.101
 * /raven/mav_linear_mpc/roll_max: 0.436332312999
 * /raven/mav_linear_mpc/roll_time_constant: 0.253
 * /raven/mav_linear_mpc/sampling_time: 0.02
 * /raven/mav_linear_mpc/thrust_max: 20
 * /raven/mav_linear_mpc/thrust_min: 5
 * /raven/mav_linear_mpc/use_rc_teleop: True
 * /raven/mav_linear_mpc/verbose: False
 * /raven/mav_linear_mpc/yaw_rate_max: 1.57079632679
 * /raven/pose_sensor_rovio/core/core_noise_acc: 0.083
 * /raven/pose_sensor_rovio/core/core_noise_accbias: 5e-05
 * /raven/pose_sensor_rovio/core/core_noise_gyr: 0.0013
 * /raven/pose_sensor_rovio/core/core_noise_gyrbias: 1.3e-06
 * /raven/pose_sensor_rovio/core/data_playback: True
 * /raven/pose_sensor_rovio/core/fixed_bias: 0
 * /raven/pose_sensor_rovio/pose_sensor/fixed_scale: 1.0
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/x: 0.0312049862392
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/y: 0.0639849685927
 * /raven/pose_sensor_rovio/pose_sensor/init/p_ic/z: -0.0618914813697
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/w: 0.0318837925519
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/x: 0.704754446355
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/y: -0.708229159884
 * /raven/pose_sensor_rovio/pose_sensor/init/q_ic/z: -0.0267591331242
 * /raven/pose_sensor_rovio/pose_sensor/pose_absolute_measurements: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_delay: -0.0358408930047
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_p_ic: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_p_wv: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_q_ic: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_q_wv: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_fixed_scale: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_measurement_world_sensor: True
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_meas_p: 0.2
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_meas_q: 0.09
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_p_ic: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_p_wv: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_q_ic: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_q_wv: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_noise_scale: 0.0
 * /raven/pose_sensor_rovio/pose_sensor/pose_use_fixed_covariance: True
 * /raven/trajectory_sampler/publish_whole_trajectory: True
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /raven/
    dji_interface (dji_interface/dji_interface_node)
    mav_linear_mpc (mav_linear_mpc/mav_linear_mpc_node)
    pose_sensor_rovio (msf_updates/pose_sensor)
    trajectory_sampler (mav_trajectory_generation_ros/trajectory_sampler_node)
    world_to_odom (tf/static_transform_publisher)
    world_to_vicon (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [7782]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 28784fd4-6fb4-11e8-b801-e0d55e131bd1
process[rosout-1]: started with pid [7795]
started core service [/rosout]
process[raven/dji_interface-2]: started with pid [7815]
process[raven/pose_sensor_rovio-3]: started with pid [7816]
device: /dev/ttyUSB0
process[raven/mav_linear_mpc-4]: started with pid [7829]
process[raven/trajectory_sampler-5]: started with pid [7842]
drone_version: M100
process[raven/world_to_vicon-6]: started with pid [7852]
process[raven/world_to_odom-7]: started with pid [7874]
INFO] [1528968020.290782468]: parameters loaded correctly
ERROR openSerial,line 169: Failed to open serial device /dev/ttyUSB0
ERROR init,line 58: Failed to start serial device
INFO] [1528968020.290898179]: Succeed to create thread for readPoll and sendPoll
INFO] [1528968020.303941389]: Initialized trajectory sampler.
INFO] [1528968020.310705879]: start initializing mav_disturbance_observer:KF
INFO] [1528968020.312381923]: mav_disturbance_observer:KF dynamic config is called successfully
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0614 17:20:20.313879  7842 trajectory_sampling.cpp:38] Dimension has to be 3 or 4, but is 0
[ INFO] [1528968020.316597358]: /raven/pose_sensor_rovio:
	subscribed to topics:
	advertised topics:
		/rosout
		/tf
		/raven/pose_sensor_rovio/core/parameter_descriptions
		/raven/pose_sensor_rovio/core/parameter_updates
		/raven/msf_core/state_out
		/raven/msf_core/correction
		/raven/msf_core/pose
		/raven/msf_core/odometry
		/raven/msf_core/pose_after_update
		/raven/msf_core/ext_state
		/raven/msf_core/cov_core
		/raven/msf_core/cov_aux
		/raven/msf_core/cov_core_aux

INFO] [1528968020.324465781]: Loading parameters for pose sensor from namespace: /raven/pose_sensor_rovio/pose_sensor
INFO] [1528968020.330612310]: Pose sensor is interpreting measurement as sensor w.r.t. world
INFO] [1528968020.330673043]: Pose sensor is using fixed covariance
INFO] [1528968020.330693100]: Pose sensor is handling measurements as absolute values
INFO] [1528968020.339987501]: KF parameters loaded successfully
INFO] [1528968020.340419490]: state_covariance_: 
0.1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0 0.1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0 0.1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   0 0.1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   0   0 0.1   0   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   0   0   0 0.1   0   0   0   0   0   0   0   0   0   0   0   0
  0   0   0   0   0   0 0.1   0   0   0   0   0   0   0   0   0   0   0
  0   0   0   0   0   0   0 0.1   0   0   0   0   0   0   0   0   0   0
  0   0   0   0   0   0   0   0 0.1   0   0   0   0   0   0   0   0   0
  0   0   0   0   0   0   0   0   0 0.1   0   0   0   0   0   0   0   0
  0   0   0   0   0   0   0   0   0   0 0.1   0   0   0   0   0   0   0
  0   0   0   0   0   0   0   0   0   0   0 0.1   0   0   0   0   0   0
  0   0   0   0   0   0   0   0   0   0   0   0 0.1   0   0   0   0   0
  0   0   0   0   0   0   0   0   0   0   0   0   0 0.1   0   0   0   0
  0   0   0   0   0   0   0   0   0   0   0   0   0   0 0.1   0   0   0
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 0.1   0   0
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 0.1   0
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 0.1
INFO] [1528968020.340479598]: Kalman Filter Initialized!
INFO] [1528968020.349571808]: Linear MPC: Steady State calculation is initialized correctly
INFO] [1528968020.349627382]: Linear MPC: initialized correctly
INFO] [1528968020.393949228]: Linear MPC: Tuning parameters updated...
INFO] [1528968020.416135212]: Created control interface for controller linear_model_predictive_controller and RC ACI rc interface
ERROR sendData,line 47: Port closedERROR sendData,line 47: Port closedERROR sendData,line 47: Port closed==============
DJI Comm initialized correctly.
Hardware : 
Firmware : 0x00
==============
ERROR activate,line 391: Please call getDroneVersion first.
ERROR sendData,line 47: Port closedBroadcast call back received 
WARN] [1528968021.406101655]: No odometry message received in the last 1 seconds! -- going back to manual remote control
WARN] [1528968022.405802427]: No odometry message received in the last 1 seconds! -- going back to manual remote control
WARN] [1528968023.405300518]: No odometry message received in the last 1 seconds! -- going back to manual remote control
^C[raven/world_to_odom-7] killing on exit
[raven/world_to_vicon-6] killing on exit

![image]
(https://github.com/wqwanghanzhang/wq_picture/blob/master/798224851.jpg)

**Comment by wqwanghanzhang** [comment]
Hi,inkyusa
I've found the reason.I have't notice the page:N1 Autopilot before,and After the configuration by following this page,I get the right world-imu(drone)-imu(zr300) coordinate system in rviz.thank you again!
