### ISSUE TITLE
some questions about the tutorial

### ISSUE THREAD

**Issue by wqwanghanzhang** [ethz-asl/mav_dji_ros_interface#28]
Hello,thanks for the sharing

I am really appreciate your amazing job,but I still have some questions about it.and I notice @inkyusa and @fmina you have been working on this.can you give me some light on this?
I've follow this tutorials for about 2 months,and I found some questions and I can't handle it by myself.

1.about "Dynamic System Identification (via VirtualRC)". I found some information from issues that it has been Deprecated since last year and I won't use the Logitec Gamepad F710 to control the M100 any more, because  you use attitude thrust to replace z velocity.(https://github.com/ethz-asl/mav_dji_ros_interface/issues/21).
so my first question is:should I use the DJI's remote control to control the M100 or others like keyboard?
The Dynamic System Identification (via attitudeThrust) page is not updated,I know it has been a long time since you have finished this section,and you must don't have time on it ,all I need to know is if this section is important to the flight?can I just skip this section and directly do the job in "First Autonomous Flight: Hover and Step Response"section after I finished the job in "MPC with MSF and ROVIO"  section?because I found the "First Autonomous Flight: Hover and Step Response" just need the steps in the "MPC with MSF and ROVIO"  section.

2.about First Autonomous Flight: Hover and Step Response:

1).when I do this job in simulation environment  by using DJI Assistant2 software,I've a question about step6 :
> Now all modules are up and running in position control mode (i.e., you send position commands via the transmitter not attitude commands). Slowly increase desired z position.

Does that mean I have to use the Dji's remote control to increase desired z position?if yes ,I've found I can't control the M100 nicely in simulation environment,no matter how Slowly I push the Remote control rod up,the z position will increase without stopping and no matter how Slowly I push the Remote control rod down,the z position will decrease without stopping.I can't make it stay in a fixed hight and it will drift a lot on x and y axles,but it can still response to my remote controller.when I publish topic message like fly 1 meter high via rqt the M100 in dji assistan2(simulation) didn't response.  this question is crucial to me.I guess if there are some parameter files I missed.
I notice the launch file has load a dji_interface_params.yaml file  in /cfg/raven/  folder but the frequency of some sensor are different from the parameters in params.yaml which is located in  /cfg/ folder
Here is params.yaml:
> device: "/dev/ttyUSB0"
> app_id: 1040678
> enc_key: "a41335b074411eb3408029cd0955324df2d3b84e5c0d80ed8344ae5c34e05cb2"
> thrust_minimum: 10
> thrust_maximum: 100
> thrust_offset: 8.945
> thrust_coefficient: 0.7389
> 
> #available freq: 0 1 10 50 100 Hz
> imu_update_rate: 50
> gps_updae_rate: 10
> time_stamp_update_rate: 1
> magnetometer_update_rate: 10
> rc_update_rate: 50
> status_update_rate: 10 

Here is dji_interface_params.yaml:
> device: "/dev/ttyUSB0" #"/dev/tty.usbserial-A104JS3T"
> app_id: 1040678
> enc_key: "a41335b074411eb3408029cd0955324df2d3b84e5c0d80ed8344ae5c34e05cb2"
> thrust_constant: 1.2
> baudrate: 921600
> #921600, 
> #available freq: 0 1 10 50 100 Hz
> imu_update_rate: 50 #100
> gps_updae_rate: 1
> time_stamp_update_rate: 1
> magnetometer_update_rate: 1
> rc_update_rate: 10
> status_update_rate: 1

the frequency of status_update_rate,rc_update_rate,magnetometer_update_rate,gps_updae_rate are different.so which one is correct? need I modify the parameters?and Do these parameters have connection with the fly drift?

Here are the screenshots of my experiment:(the world-imu(M100)-imu(zr300) coordinate is stable)
![1.the screenshot of rovio](https://github.com/wqwanghanzhang/wq_picture/blob/master/Screenshot%20from%202018-06-25%2014:26:40.png)

![2.the world-imu(M100)-imu(zr300) in rviz](https://github.com/wqwanghanzhang/wq_picture/blob/master/Screenshot%20from%202018-06-25%2014:25:06.png)

**Comment by inkyusa** [comment]
Hello wqwanghanzhang,
Sorry for delayed response.
For the first question,

> 1.about "Dynamic System Identification (via VirtualRC)". I found some information from issues that it has been Deprecated since last year and I won't use the Logitec Gamepad F710 to control the M100 any more, because you use attitude thrust to replace z velocity.(#21).
> so my first question is:should I use the DJI's remote control to control the M100 or others like keyboard?

In case your drone keeps the similar configuration what we used (intel nuc and vi-sensor center mounted), you can test with the same parameters. Could you tell more about your drone configuration?

**Comment by inkyusa** [comment]
Hello wqwanghanzhang,
Sorry for delayed reply.
Yes, we configure the DJI autopilot setting as we want (please have a look https://github.com/ethz-asl/mav_dji_ros_interface/blob/951df2853cffc438726ea6be2c4308f3dbf9b099/dji_interface/src/dji_interface.cpp#L99 and https://github.com/ethz-asl/mav_dji_ros_interface/blob/951df2853cffc438726ea6be2c4308f3dbf9b099/dji_interface/cfg/params.yaml).
We found that there is some RS232 bandwidth issue in communicating between N1 (M100 autopilot) and NUC (a computer) so that these parameter setup were tuned for working properly.
Hope this help, best
