### ISSUE TITLE
Classic PID for x/y axis position control

### ISSUE THREAD

**Issue by rocklinsuv** [ethz-asl/mav_dji_ros_interface#30]
Hi Community,

After reading your FSR paper I realized that you used classic PID for z control. I'm wondering if you have ever tried PID for x and y control under HORIZONTAL_ANGLE mode ( according the original Onboard-SDK-ROS)? I have a set of UltraSonic sensor to give me position and velocity, not as accurate as VICON but acceptable precision. I followed the traditional PID tuning guide to increase the P term from 0.1 to 5 and never had it converge. If you have tried classic PID, would you be able to provide some hints on the values? Many thanks.

BR,
rocklinsuv

**Comment by inkyusa** [comment]
Hello rocklinsuv,
Our previous version used PID for z velocity control and the current version in this repo makes use of nMPC for controlling 4 dof (i.e., x,y,z and yaw). Hope this answer to your question.
