### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Bifzivkar** [ethz-asl/mav_dji_ros_interface#32]
![image](https://user-images.githubusercontent.com/20577473/50534165-dab5c180-0b73-11e9-8500-6846112b0204.png)

**Comment by Bifzivkar** [comment]
hello，how to solve this problem and why

![image](https://user-images.githubusercontent.com/20577473/50534187-29fbf200-0b74-11e9-908f-992823875f21.png)

**Comment by yiweijian** [comment]
> 你好，如何解决这个问题以及为什么
> 
> ![图片](https://user-images.githubusercontent.com/20577473/50534187-29fbf200-0b74-11e9-908f-992823875f21.png)

Oh, I met the same problem with you ,would you solve it?

**Comment by inkyusa** [comment]
Hello,
The error seems to relate realsense2_camera package and not related to this repo.
For the ZR300 driver, we use our customized drivers (https://github.com/inkyusa/realsense_ros_simple) and (https://github.com/inkyusa/ze_deps). 
Could you try these instead realsense2_camera package?

**Comment by Bifzivkar** [comment]
@inkyusa Thank you very much, this method solved our problem.
