### ISSUE TITLE
Replace rovio with vins-mono

### ISSUE THREAD

**Issue by Bifzivkar** [ethz-asl/mav_dji_ros_interface#33]
In this system, can I replace rovio with vins-mono? if it is possible，How to replace？

**Comment by inkyusa** [comment]
As far as you can feed odometry information to MSF, I think it is possible. If you already have odometry topic (as transform message type), then try to rename the input topic name in the launch file.
For example, https://github.com/ethz-asl/mav_dji_ros_interface/blob/master/dji_interface/launch/raven_indoor_rovio_nMPC_trj.launch in this file, MSF takes "<remap from="msf_updates/transform_input" to="rovio/transform" />" as input which is output transfrom from rovio. Replacing this with vins output should work.

It is suggested to qualitatively evaluate rovio+MSF and vins-mono+MSF output (i.e., estimated state) before any autonomous flights...
It is interesting to see how your project goes with vins and our repo.
